---
# tasks file for roles/database
- name: Run Database
  docker_container:
    name: database
    image: maximebattu/docker-database
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
    - name: app-network