version: '3.7'

services:
    backend-blue:
        build: /api/
        container_name: api1
        ports:
          - 8081:8080
        networks:
          - app-network
        depends_on:
          - database

    backend-green:
        build: /api/
        container_name: api2
        ports:
          - 8082:8080
        networks:
          - app-network
        depends_on:
          - database

    database:
        build: /data/
        container_name: database
        networks:
          - app-network

    httpd:
        build: /http/
        container_name: apache
        ports:
          - 82:80
        networks:
          - app-network
        depends_on:
          - backend-blue
          - backend-green
    
    front:
        build: /front/
        container_name: vue
        ports:
          - 80:80
        networks:
          - app-network
        depends_on:
          - httpd

networks:
    app-network:
      driver: bridge