---
# tasks file for roles/app
- name: Run API 1
  docker_container:
    name: api1
    image: maximebattu/docker-api
    networks:
    - name: app-network
    ports:
      - 8081:8080
  
- name: Run API 2
  docker_container:
    name: api2
    image: maximebattu/docker-api
    networks:
    - name: app-network
    ports:
      - 8082:8080